version: 0.2
os: windows
phases:   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./WebApi/WebApi.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build ./WebApi/WebApi.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r windows-x64 --self-contained false ./WebApi/WebApi.csproj
      
artifacts:
  files:
    - '**/*'
  discard-paths: no
