// <auto-generated />
using System;
using Domain.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.DataAccess.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.UserManagement.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("DataAccess.UserManagement.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DataAccess.UserManagement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccess.UserManagement.UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DataAccess.UserManagement.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTokenType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.Education.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUpToPresent")
                        .HasColumnType("bit");

                    b.Property<int>("KidProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CityId");

                    b.HasIndex("KidProfileId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.KidProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Impairment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParrentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ParrentId");

                    b.ToTable("KidProfiles");
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.SuperPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SuperPowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Musician (playing an instrument). Piano",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Musician (playing an instrument). Guitar",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Musician (playing an instrument). Drums",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Singer. Yodeler",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Singer. Country singer",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Singer. Band",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Singer. Country",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Singer. Opera singer",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Singer. Lip sync",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Choir",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Jazz Band",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Marching band",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Orchestra",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Percussion",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Song writer",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "DJ",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Drummer",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Solo dancer",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 21,
                            Name = "Dance group",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 22,
                            Name = "Dance troupe",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hip Hop",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ballet",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ballroom",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 26,
                            Name = "Contemporary",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 27,
                            Name = "Jazz",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 28,
                            Name = "Tap Dance",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 29,
                            Name = "Folk Dance",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 30,
                            Name = "Irish Dance",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 31,
                            Name = "Modern Dance",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 32,
                            Name = "Swing Dance",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 33,
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.SuperPowerToKid", b =>
                {
                    b.Property<int>("KidId")
                        .HasColumnType("int");

                    b.Property<int>("SuperPowerId")
                        .HasColumnType("int");

                    b.HasKey("KidId", "SuperPowerId");

                    b.HasIndex("SuperPowerId");

                    b.ToTable("SuperPowerToKid");
                });

            modelBuilder.Entity("Domain.DataAccess.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToConferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ToDeskId")
                        .HasColumnType("int");

                    b.Property<int?>("ToFloorId")
                        .HasColumnType("int");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Domain.DataAccess.Models.MessageAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("Domain.DataAccess.Models.StripeProductInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("PriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StripeProductsInfo");
                });

            modelBuilder.Entity("Domain.DataAccess.Models.UserCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserCustomers");
                });

            modelBuilder.Entity("Payment.DataAccess.Enitities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "key",
                            Name = "Name"
                        });
                });

            modelBuilder.Entity("Payment.DataAccess.Enitities.SubscriptionFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool?>("FlagValue")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeatureId = 1,
                            NumberValue = 100m,
                            SubscriptionPlanId = 1
                        });
                });

            modelBuilder.Entity("Payment.DataAccess.Enitities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Annual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FreeTrialPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FreeTrialPeriod = 1,
                            Name = "Organizer",
                            Price = 99m,
                            Type = 2
                        });
                });

            modelBuilder.Entity("UserManagement.DataAccess.UserManagement.Location.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("UserManagement.DataAccess.UserManagement.Location.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("UserManagement.DataAccess.UserManagement.Location.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("DataAccess.UserManagement.Company", b =>
                {
                    b.HasOne("Payment.DataAccess.Enitities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.UserManagement.User", b =>
                {
                    b.HasOne("DataAccess.UserManagement.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.UserManagement.UserRoles", b =>
                {
                    b.HasOne("DataAccess.UserManagement.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.UserManagement.UserToken", b =>
                {
                    b.HasOne("DataAccess.UserManagement.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.Education.Education", b =>
                {
                    b.HasOne("DataAccess.UserManagement.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UserManagement.DataAccess.UserManagement.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.DataAccess.Entities.KidProfile.KidProfile", "KidProfile")
                        .WithMany()
                        .HasForeignKey("KidProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.KidProfile", b =>
                {
                    b.HasOne("UserManagement.DataAccess.UserManagement.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccess.UserManagement.User", "Parrent")
                        .WithMany()
                        .HasForeignKey("ParrentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.SuperPower", b =>
                {
                    b.HasOne("Domain.DataAccess.Entities.KidProfile.SuperPower", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Domain.DataAccess.Entities.KidProfile.SuperPowerToKid", b =>
                {
                    b.HasOne("Domain.DataAccess.Entities.KidProfile.KidProfile", "Kid")
                        .WithMany("SuperPowers")
                        .HasForeignKey("KidId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.DataAccess.Entities.KidProfile.SuperPower", "SuperPower")
                        .WithMany()
                        .HasForeignKey("SuperPowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DataAccess.Models.MessageAttachment", b =>
                {
                    b.HasOne("Domain.DataAccess.Models.Message", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Payment.DataAccess.Enitities.SubscriptionFeature", b =>
                {
                    b.HasOne("Payment.DataAccess.Enitities.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Payment.DataAccess.Enitities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionFeatures")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagement.DataAccess.UserManagement.Location.City", b =>
                {
                    b.HasOne("UserManagement.DataAccess.UserManagement.Location.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagement.DataAccess.UserManagement.Location.Region", b =>
                {
                    b.HasOne("UserManagement.DataAccess.UserManagement.Location.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
